version: '3'

services:
  app:
    container_name: flaskapp
    build: ./app/
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    env_file: .env
    depends_on:
      - db
    links:
      - db
  db:
    container_name: flaskdb
    build: ./db/
    env_file: .env